services:

  canton:
    container_name: canton
    image: digitalasset/canton-open-source:2.7.9
    volumes:
      - ./configs:/canton/host/configs
    command: daemon --config "/canton/host/configs/canton.conf" --bootstrap "/canton/host/configs/bootstrap.canton" --log-profile container --log-level-root INFO
    expose:
      - "5001-5006:5001-5006"
    ports:
      - "5001-5006:5001-5006"

  mockauth:
    container_name: mockauth
    image: ghcr.io/navikt/mock-oauth2-server:2.1.4
    volumes:
      - ./configs:/configs
    environment:
      - SERVER_PORT=80
      - JSON_CONFIG_PATH=/configs/mockauth.json
    expose:
      - "80:80"
    ports:
      - "8080:80"

  console:
    container_name: console
    image: mock-oauth2-demo-console
    build:
      context: console/
      dockerfile: Dockerfile
    volumes:
      - ./configs:/home/daml/configs
